#!/usr/bin/env python3
"""
Exhaustive 3-edge-colourability check for cubic Cayley graphs on small
non-solvable groups.

A connected cubic Cayley graph Cay(G,S) has either S = {a,b,c} (three
involutions) or S = {a, x, x^{-1}} with a an involution and ord(x) >= 3.
The first case, and the second case with ord(x) even, are trivially
3-edge-colourable.  So only S = {a, x, x^{-1}} with ord(x) odd needs to be
checked.  For each group below we enumerate every such generating pair
(a, x) up to conjugation in G and inversion of x, build the Cayley graph and
decide 3-edge-colourability with a SAT solver (CaDiCaL via python-sat).

Groups are given as permutation groups; group orders are verified against
the known formulas, and the Petersen graph is used as a negative control.

Run:  python3 cayley_snark_check.py [max_order]
"""
import sys, time, itertools
from pysat.solvers import Cadical153

# ----------------------------------------------------------------- permutations
def mul(p, q):
    """Apply p first, then q (so that mul(p,q)(i) = q[p[i]])."""
    return tuple(q[i] for i in p)

def inv(p):
    r = [0] * len(p)
    for i, j in enumerate(p):
        r[j] = i
    return tuple(r)

def order(p):
    e = tuple(range(len(p)))
    k, q = 1, p
    while q != e:
        q = mul(q, p)
        k += 1
    return k

def closure(gens):
    """All elements of the group generated by gens (BFS)."""
    n = len(gens[0])
    e = tuple(range(n))
    seen = {e}
    frontier = [e]
    while frontier:
        new = []
        for g in frontier:
            for s in gens:
                h = mul(g, s)
                if h not in seen:
                    seen.add(h)
                    new.append(h)
        frontier = new
    return seen

def generates(gens, target_size):
    """Does <gens> have order target_size?  (BFS with early abort.)"""
    n = len(gens[0])
    e = tuple(range(n))
    seen = {e}
    frontier = [e]
    while frontier:
        new = []
        for g in frontier:
            for s in gens:
                h = mul(g, s)
                if h not in seen:
                    seen.add(h)
                    new.append(h)
        frontier = new
    return len(seen) == target_size

# ----------------------------------------------------------------- finite fields
class GF:
    """GF(q), q = p^k, elements are integers 0..q-1 encoding polynomials in base p."""
    IRRED = {8: (2, [1, 1, 0, 1]),      # x^3 + x + 1
             9: (3, [1, 0, 1]),         # x^2 + 1
             16: (2, [1, 1, 0, 0, 1]),  # x^4 + x + 1
             25: (5, [2, 0, 1]),        # x^2 + 2  (2 is a non-square mod 5)
             27: (3, [1, 2, 0, 1]),     # x^3 + 2x + 1
             32: (2, [1, 0, 1, 0, 0, 1]),  # x^5 + x^2 + 1
             49: (7, [1, 0, 1]),         # x^2 + 1  (7 = 3 mod 4)
             64: (2, [1, 1, 0, 0, 0, 0, 1])}  # x^6 + x + 1

    def __init__(self, q):
        self.q = q
        if all(q % p for p in range(2, q)):     # prime
            self.p, self.k = q, 1
            self.add = lambda a, b: (a + b) % q
            self.mulf = lambda a, b: (a * b) % q
            self.neg = lambda a: (-a) % q
        else:
            p, poly = self.IRRED[q]
            self.p = p
            k = len(poly) - 1
            self.k = k
            def digits(a):
                d = []
                for _ in range(k):
                    d.append(a % p); a //= p
                return d
            def undig(d):
                a = 0
                for c in reversed(d):
                    a = a * p + c
                return a
            def add(a, b):
                return undig([(x + y) % p for x, y in zip(digits(a), digits(b))])
            def neg(a):
                return undig([(-x) % p for x in digits(a)])
            def mulf(a, b):
                da, db = digits(a), digits(b)
                prod = [0] * (2 * k - 1)
                for i, x in enumerate(da):
                    for j, y in enumerate(db):
                        prod[i + j] = (prod[i + j] + x * y) % p
                # reduce modulo poly (monic, degree k)
                for i in range(2 * k - 2, k - 1, -1):
                    c = prod[i]
                    if c:
                        for j in range(k + 1):
                            prod[i - k + j] = (prod[i - k + j] - c * poly[j]) % p
                return undig(prod[:k])
            self.add, self.neg, self.mulf = add, neg, mulf
        self.inv_table = {}
        for a in range(1, q):
            for b in range(1, q):
                if self.mulf(a, b) == 1:
                    self.inv_table[a] = b
                    break
        # primitive element
        for z in range(2, q):
            x, n = 1, 0
            while True:
                x = self.mulf(x, z); n += 1
                if x == 1:
                    break
            if n == q - 1:
                self.zeta = z
                break

# ----------------------------------------------------------------- groups
def psl2(q, projective_general=False, frob=None, frob_diag=False, expected=None):
    """PSL(2,q) (or PGL(2,q)) acting on the projective line, as permutations
    of {0..q-1} ∪ {q = ∞}.  If frob = e, the field automorphism x -> x^e is
    added (giving PSigmaL-type extensions); with frob_diag the element
    x -> zeta x^e is added instead (giving M10-type extensions)."""
    F = GF(q)
    INF = q
    pts = list(range(q + 1))
    def perm(f):
        return tuple(f(x) for x in pts)
    def translate(x):
        return INF if x == INF else F.add(x, 1)
    z = F.zeta
    zsq = F.mulf(z, z)
    m = z if (projective_general or q % 2 == 0) else zsq
    def scale(x):
        return INF if x == INF else F.mulf(m, x)
    def invert(x):            # x -> -1/x
        if x == INF: return 0
        if x == 0: return INF
        return F.neg(F.inv_table[x])
    gens = [perm(translate), perm(scale), perm(invert)]
    if frob is not None:
        def power(x, e):
            r = 1
            for _ in range(e): r = F.mulf(r, x)
            return r
        def fa(x):
            if x == INF: return INF
            v = power(x, frob)
            return F.mulf(z, v) if frob_diag else v
        gens.append(perm(fa))
    G = closure(gens)
    d = 1 if (q % 2 == 0 or projective_general) else 2
    if expected is None:
        expected = q * (q * q - 1) // d
    assert len(G) == expected, (q, len(G), expected)
    return G

def m10():
    G = psl2(9, frob=3, frob_diag=True, expected=720)
    assert G != psl2(9, True) and G != psl2(9, frob=3, expected=720)
    return G

def wreath_A5_Z2():
    c3 = tuple([1, 2, 0, 3, 4] + list(range(5, 10)))
    c5 = tuple([1, 2, 3, 4, 0] + list(range(5, 10)))
    sw = tuple(list(range(5, 10)) + list(range(5)))
    G = closure([c3, c5, sw])
    assert len(G) == 7200
    return G

def alternating(n):
    gens = []
    # 3-cycles (0 1 2), and (0 1 ... n-1) or (1 ... n-1) depending on parity
    c3 = list(range(n)); c3[0], c3[1], c3[2] = 1, 2, 0
    if n % 2 == 1:
        cyc = list(range(1, n)) + [0]
    else:
        cyc = [0] + list(range(2, n)) + [1]
    G = closure([tuple(c3), tuple(cyc)])
    import math
    assert len(G) == math.factorial(n) // 2
    return G

def symmetric(n):
    import math
    t = list(range(n)); t[0], t[1] = 1, 0
    cyc = list(range(1, n)) + [0]
    G = closure([tuple(t), tuple(cyc)])
    assert len(G) == math.factorial(n)
    return G

def m11():
    # standard generators of M11 on 11 points (0-based)
    a = tuple((i + 1) % 11 for i in range(11))
    # (3,7,11,8)(4,10,5,6) in 1-based notation
    b = list(range(11))
    for cyc in [(3, 7, 11, 8), (4, 10, 5, 6)]:
        for i in range(len(cyc)):
            b[cyc[i] - 1] = cyc[(i + 1) % len(cyc)] - 1
    G = closure([a, tuple(b)])
    assert len(G) == 7920
    return G

def psl3_3():
    # PSL(3,3) acting on the 13 points of PG(2,3)
    p = 3
    pts = []
    seen = set()
    for v in itertools.product(range(p), repeat=3):
        if v == (0, 0, 0): continue
        # normalise: first nonzero coordinate = 1
        for c in v:
            if c: break
        cinv = 1 if c == 1 else 2
        w = tuple((cinv * x) % p for x in v)
        if w not in seen:
            seen.add(w); pts.append(w)
    idx = {v: i for i, v in enumerate(pts)}
    def act(M):
        out = []
        for v in pts:
            w = tuple(sum(M[i][j] * v[j] for j in range(3)) % p for i in range(3))
            for c in w:
                if c: break
            cinv = 1 if c == 1 else 2
            w = tuple((cinv * x) % p for x in w)
            out.append(idx[w])
        return tuple(out)
    gens = [act([[1, 1, 0], [0, 1, 0], [0, 0, 1]]),
            act([[0, 0, 1], [1, 0, 0], [0, 1, 0]]),
            act([[1, 0, 0], [0, 1, 1], [0, 0, 1]])]
    G = closure(gens)
    assert len(G) == 5616, len(G)
    return G

# ----------------------------------------------------------------- SAT colouring
def three_edge_colourable(n, edges, time_limit=None):
    """Decide 3-edge-colourability of a cubic (multi)graph.

    Encoding: choose a perfect matching M (one colour class) such that the
    complementary 2-factor is bipartite, i.e. consists of even cycles.
    Variables m_e (e in M) and b_v (side of v in the 2-colouring of the
    2-factor).  Symmetry breaking: the first edge at vertex 0 lies in M and
    b_0 = 0 (colour classes may be renamed, and the 2-colouring flipped).

    Returns (True, colouring) / (False, None) / (None, None) on timeout,
    where colouring is a list of colours 0,1,2 indexed by edge."""
    m = lambda e: e + 1
    b = lambda v: len(edges) + v + 1
    inc = [[] for _ in range(n)]
    for e, (u, v) in enumerate(edges):
        inc[u].append(e); inc[v].append(e)
    s = Cadical153()
    for v in range(n):
        L = inc[v]
        assert len(L) == 3
        s.add_clause([m(e) for e in L])
        for i in range(3):
            for j in range(i + 1, 3):
                s.add_clause([-m(L[i]), -m(L[j])])
    for e, (u, v) in enumerate(edges):
        s.add_clause([m(e), b(u), b(v)])
        s.add_clause([m(e), -b(u), -b(v)])
    s.add_clause([m(inc[0][0])])
    s.add_clause([-b(0)])
    if time_limit is not None:
        # CaDiCaL cannot be interrupted from Python: solve in a forked child
        # process and kill it if it exceeds the limit.
        s.delete()
        return _solve_in_child(n, edges, time_limit)
    r = s.solve()
    if r is None:
        s.delete(); return None, None
    if not r:
        s.delete(); return False, None
    model = set(l for l in s.get_model() if l > 0)
    s.delete()
    M = set(e for e in range(len(edges)) if m(e) in model)
    side = [1 if b(v) in model else 0 for v in range(n)]
    # colour: M -> 2; a non-M edge uv gets colour side[u] where u is the
    # endpoint listed first in the ordering that walks each 2-factor cycle.
    # Simpler: colour the 2-factor cycles by walking them.
    col = [-1] * len(edges)
    for e in M:
        col[e] = 2
    nxt = [[] for _ in range(n)]
    for e, (u, v) in enumerate(edges):
        if e not in M:
            nxt[u].append((e, v)); nxt[v].append((e, u))
    for v0 in range(n):
        if all(col[e] >= 0 for e, _ in nxt[v0]):
            continue
        v, c = v0, 0
        prev_e = None
        while True:
            cand = [(e, w) for e, w in nxt[v] if col[e] < 0]
            if not cand:
                break
            e, w = cand[0]
            col[e] = c; c ^= 1; v = w
    assert all(c >= 0 for c in col)
    check_colouring(n, edges, col)
    return True, col

def _solve_in_child(n, edges, time_limit):
    import os, pickle, select
    r, w = os.pipe()
    pid = os.fork()
    if pid == 0:                       # child
        os.close(r)
        try:
            data = pickle.dumps(three_edge_colourable(n, edges))
        except Exception:
            data = pickle.dumps((None, None))
        while data:
            k = os.write(w, data); data = data[k:]
        os.close(w)
        os._exit(0)
    os.close(w)
    chunks, deadline = [], time.time() + time_limit
    while True:
        remaining = deadline - time.time()
        if remaining <= 0:
            os.kill(pid, 9); os.waitpid(pid, 0); os.close(r)
            return None, None
        rl, _, _ = select.select([r], [], [], remaining)
        if rl:
            chunk = os.read(r, 1 << 16)
            if not chunk:
                break
            chunks.append(chunk)
    os.close(r); os.waitpid(pid, 0)
    return pickle.loads(b"".join(chunks))

def check_colouring(n, edges, col):
    at = [set() for _ in range(n)]
    for e, (u, v) in enumerate(edges):
        assert col[e] in (0, 1, 2)
        assert col[e] not in at[u] and col[e] not in at[v]
        at[u].add(col[e]); at[v].add(col[e])
    assert all(len(a) == 3 for a in at)

def petersen_control():
    edges = [(i, (i + 1) % 5) for i in range(5)] + \
            [(5 + i, 5 + (i + 2) % 5) for i in range(5)] + \
            [(i, i + 5) for i in range(5)]
    assert three_edge_colourable(10, edges)[0] is False
    cube = [(0,1),(1,2),(2,3),(3,0),(4,5),(5,6),(6,7),(7,4),(0,4),(1,5),(2,6),(3,7)]
    assert three_edge_colourable(8, cube)[0] is True

# ----------------------------------------------------------------- main check
_ELEMS = _INDEX = _ORDS = None
FULL_SAT_TIME_LIMIT = 300.0   # seconds
QUOTIENT_TIME_LIMIT = 20.0    # seconds per quotient attempt
MAX_QUOTIENTS = 12

def cayley_edges(elems, index, a, x):
    """Edges of Cay(G,{a,x,x^-1}); returns (edges, label) with label 'a'/'x'."""
    N = len(elems)
    edges, lab = [], []
    for g in elems:
        gi = index[g]
        ha, hx = index[mul(g, a)], index[mul(g, x)]
        if gi < ha:
            edges.append((gi, ha)); lab.append('a')
        edges.append((gi, hx)); lab.append('x')
    assert len(edges) == 3 * N // 2
    return edges, lab

def quotient_by_subgroup(elems, index, H, a, x):
    """Quotient of Cay(G,{a,x,x^-1}) by the left action of the subgroup H.
    H must contain no conjugate of a or of x; then the quotient is a cubic
    loopless multigraph and Cay -> quotient is a covering.
    Returns (n, edges, vertex_of_g, edge_of_(g,label))."""
    N = len(elems)
    coset = [-1] * N
    reps = []
    for g in elems:
        gi = index[g]
        if coset[gi] >= 0:
            continue
        cid = len(reps); reps.append(g)
        for h in H:
            coset[index[mul(h, g)]] = cid
    n = len(reps)
    edges = []
    for cid, g in enumerate(reps):
        edges.append((cid, coset[index[mul(g, a)]]))   # a-edge (edge index 2*cid)
        edges.append((cid, coset[index[mul(g, x)]]))   # x-edge (edge index 2*cid+1)
    # the a-edge of coset c appears twice (once from each end); dedupe:
    # a-edge from c and from c' = coset(g a) are the same edge.
    ded, amap = [], {}
    for cid, g in enumerate(reps):
        c2 = coset[index[mul(g, a)]]
        key = (min(cid, c2), max(cid, c2))
        if key not in amap:
            amap[key] = len(ded); ded.append(key)
    xstart = len(ded)
    for cid, g in enumerate(reps):
        ded.append((cid, coset[index[mul(g, x)]]))
    return n, ded, coset, amap, xstart

_SUBGROUPS = None

def odd_abelian_subgroups(elems, ords, per_order=3, max_ext=6):
    """A list of abelian subgroups of odd order (as lists of elements),
    generated by one or two commuting elements of odd order.  Used as
    covering-transformation groups for quotients."""
    reps = {}
    for y in elems:
        o = ords[y]
        if o % 2 == 1 and o > 1:
            reps.setdefault(o, [])
            if len(reps[o]) < per_order:
                reps[o].append(y)
    subs = {}
    for o, ys in reps.items():
        for y in ys:
            H = closure([y])
            subs[frozenset(H)] = list(H)
            cent = [c for c in elems if ords[c] % 2 == 1 and ords[c] > 1 and c not in H and mul(c, y) == mul(y, c)]
            tried = 0
            for z in cent:
                K = closure([y, z])
                if len(K) > len(H) and frozenset(K) not in subs:
                    subs[frozenset(K)] = list(K)
                tried += 1
                if tried >= max_ext:
                    break
    return sorted(subs.values(), key=len, reverse=True)

def decide_pair(a, x):
    """Return (True/False/None, method)."""
    elems, index, ords = _ELEMS, _INDEX, _ORDS
    N = len(elems)
    s = ords[x]
    # ---- 1. try quotients by abelian subgroups H of odd order containing no
    #         element of order s (hence no conjugate of x, and no conjugate of a)
    cands = [H for H in _SUBGROUPS if all(ords[h] != s for h in H)]
    for H in cands[:MAX_QUOTIENTS]:
        o = len(H)
        n, qedges, coset, amap, xstart = quotient_by_subgroup(elems, index, H, a, x)
        if any(u == v for u, v in qedges):
            continue          # a loop: cannot happen by the choice of H
        ok, col = three_edge_colourable(n, qedges, time_limit=QUOTIENT_TIME_LIMIT)
        if ok:
            # lift and verify on the full Cayley graph
            edges, lab = cayley_edges(elems, index, a, x)
            lifted = []
            for (u, v), l in zip(edges, lab):
                g = elems[u]
                cu = coset[u]
                if l == 'a':
                    cv = coset[v]
                    lifted.append(col[amap[(min(cu, cv), max(cu, cv))]])
                else:
                    lifted.append(col[xstart + cu])
            check_colouring(N, edges, lifted)
            return True, f"quotient by abelian subgroup of order {o} ({n} vertices)"
    # ---- 2. full SAT with a time limit
    edges, lab = cayley_edges(elems, index, a, x)
    ok, col = three_edge_colourable(N, edges, time_limit=FULL_SAT_TIME_LIMIT)
    if ok is None:
        return None, "timeout"
    if ok:
        return True, "full SAT"
    return False, "full SAT (UNSAT!)"

def _worker(args):
    a, x = args
    try:
        return decide_pair(a, x)
    except Exception as ex:      # report, never silently drop a pair
        return None, f"error: {ex!r}"

def check_group(name, G, pool=False):
    t0 = time.time()
    elems = list(G)
    index = {g: i for i, g in enumerate(elems)}
    N = len(elems)
    ords = {g: order(g) for g in elems}
    invols = [g for g in elems if ords[g] == 2]
    odd = [g for g in elems if ords[g] % 2 == 1 and ords[g] > 1]
    classes = []
    unassigned = set(invols)
    while unassigned:
        a = next(iter(unassigned))
        cls = {mul(mul(inv(g), a), g) for g in elems}
        unassigned -= cls
        classes.append((a, len(cls)))
    global _ELEMS, _INDEX, _ORDS, _SUBGROUPS
    _ELEMS, _INDEX, _ORDS = elems, index, ords
    _SUBGROUPS = odd_abelian_subgroups(elems, ords)
    pairs = []
    for a, clsize in classes:
        cent = [c for c in elems if mul(c, a) == mul(a, c)]
        cent_inv = [inv(c) for c in cent]
        seen = set()
        for x in odd:
            if x in seen:
                continue
            xi = inv(x)
            for c, ci in zip(cent, cent_inv):
                seen.add(mul(mul(ci, x), c))
                seen.add(mul(mul(ci, xi), c))
            if not generates([a, x], N):
                continue
            pairs.append((a, x))
    tested = len(pairs)
    if pool:
        import multiprocessing as mp, os
        with mp.Pool(max(1, os.cpu_count() - 1)) as P:
            outs = P.map(_worker, pairs, chunksize=1)
    else:
        outs = [_worker(p) for p in pairs]
    results = []
    methods = {}
    for (a, x), (ok, how) in zip(pairs, outs):
        s, t = ords[x], ords[mul(a, x)]
        results.append((s, t, ok, how))
        key = how.split(" (")[0]
        methods[key] = methods.get(key, 0) + 1
        if ok is False:
            print(f"!!! NON-3-EDGE-COLOURABLE CAYLEY GRAPH on {name}: ord(x)={s}, ord(ax)={t}", flush=True)
        elif ok is None:
            print(f"??? undecided pair on {name}: ord(x)={s}, ord(ax)={t}: {how}", flush=True)
    n_bad = sum(1 for r in results if r[2] is False)
    n_und = sum(1 for r in results if r[2] is None)
    print(f"{name:12s} |G|={N:6d}  involution classes={len(classes)}  "
          f"pairs (a,x) tested={tested:5d}  non-colourable={n_bad}  undecided={n_und}  "
          f"methods={methods}  [{time.time()-t0:.1f}s]", flush=True)
    return N, len(classes), tested, n_bad, n_und, results

if __name__ == "__main__":
    max_order = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    petersen_control()
    groups = [
        ("A5", lambda: alternating(5)),
        ("S5", lambda: symmetric(5)),
        ("PSL(2,7)", lambda: psl2(7)),
        ("PGL(2,7)", lambda: psl2(7, True)),
        ("A6", lambda: alternating(6)),
        ("PSL(2,8)", lambda: psl2(8)),
        ("PGL(2,9)", lambda: psl2(9, True)),
        ("S6", lambda: symmetric(6)),
        ("M10", lambda: m10()),
        ("PSL(2,11)", lambda: psl2(11)),
        ("PSL(2,13)", lambda: psl2(13)),
        ("PGL(2,11)", lambda: psl2(11, True)),
        ("PGL(2,13)", lambda: psl2(13, True)),
        ("PSL(2,17)", lambda: psl2(17)),
        ("A7", lambda: alternating(7)),
        ("PSL(2,19)", lambda: psl2(19)),
        ("PSL(2,16)", lambda: psl2(16)),
        ("PGL(2,17)", lambda: psl2(17, True)),
        ("S7", lambda: symmetric(7)),
        ("PSL(3,3)", lambda: psl3_3()),
        ("PSL(2,23)", lambda: psl2(23)),
        ("PGL(2,19)", lambda: psl2(19, True)),
        ("A5wrZ2", lambda: wreath_A5_Z2()),
        ("PSL(2,25)", lambda: psl2(25)),
        ("M11", lambda: m11()),
        ("PSigmaL(2,16)", lambda: psl2(16, frob=4, expected=8160)),
        ("PSL(2,27)", lambda: psl2(27)),
        ("PGL(2,23)", lambda: psl2(23, True)),
        ("PSL(2,29)", lambda: psl2(29)),
        ("PSL(2,31)", lambda: psl2(31)),
        ("PGL(2,25)", lambda: psl2(25, True)),
        ("PSigmaL(2,25)", lambda: psl2(25, frob=5, expected=15600)),
        ("PSL(2,25).2_3", lambda: psl2(25, frob=5, frob_diag=True, expected=15600)),
        ("PGL(2,27)", lambda: psl2(27, True)),
        ("A8", lambda: alternating(8)),
        ("PGL(2,29)", lambda: psl2(29, True)),
        ("PSL(2,37)", lambda: psl2(37)),
        ("PGL(2,31)", lambda: psl2(31, True)),
        ("PSL(2,32)", lambda: psl2(32)),
        ("PSL(2,41)", lambda: psl2(41)),
        ("PSL(2,43)", lambda: psl2(43)),
        ("PSL(2,47)", lambda: psl2(47)),
        ("PSL(2,49)", lambda: psl2(49)),
        ("S8", lambda: symmetric(8)),
    ]
    import multiprocessing as mp, json, os
    mp.set_start_method("fork")
    summary = []
    if os.path.exists("results.json"):
        summary = json.load(open("results.json"))
    done = {r["group"] for r in summary if r["undecided"] == 0}
    for name, ctor in groups:
        if ctor is None or name in done:
            continue
        G = ctor()
        if len(G) > max_order:
            continue
        N, ncls, tested, nbad, nund, results = check_group(name, G, pool=True)
        summary = [r for r in summary if r["group"] != name]
        summary.append(dict(group=name, order=N, involution_classes=ncls,
                            pairs_tested=tested, non_colourable=nbad, undecided=nund,
                            methods=sorted(set(r[3].split(" (")[0] for r in results)),
                            quotient_orders=sorted(set(int(r[3].split("order ")[1].split(" ")[0]) for r in results if "order" in r[3])),
                            orders_x=sorted(set(r[0] for r in results)),
                            pairs=sorted(set((r[0], r[1]) for r in results))))
        with open("results.json", "w") as f:
            json.dump(summary, f, indent=1)
    print("\nSUMMARY")
    for row in summary:
        print(row["group"], row["order"], row["involution_classes"], row["pairs_tested"], row["non_colourable"], row["undecided"])
